dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake
    

script:
    # Export CC and CXX to tell cmake which compiler to use
    - export CC=/usr/bin/gcc-6
    - export CXX=/usr/bin/g++-6
    # Check versions of gcc, g++ and cmake
    - gcc -v && g++ -v && cmake --version
    # Run your build commands next
    - mkdir build && cd build
    - cmake .. && make Telegram_Context